apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: horoscope
spec:
  destination:
    name: horoscope
  precedence: 1
  route:
  - labels:
      version: ominous
    weight: 50
  - labels:
      version: optimistic
    weight: 50
